// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/foundation.dart';

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      default:
        throw UnsupportedError('DefaultFirebaseOptions are not supported for this platform.');
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: "AIzaSyD4FNzAV7FackxyoWOvTh9alFYq_FdGN-Q",
    authDomain: "journal-project-comp585-fa2024.firebaseapp.com",
    projectId: "journal-project-comp585-fa2024",
    storageBucket: "journal-project-comp585-fa2024.firebasestorage.app",
    messagingSenderId: "715827816927",
    appId: "1:715827816927:web:389737f8722470b2fcbc6a",
    measurementId: "G-HV25LL906W",
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: "AIzaSyD4FNzAV7FackxyoWOvTh9alFYq_FdGN-Q",
    authDomain: "journal-project-comp585-fa2024.firebaseapp.com",
    projectId: "journal-project-comp585-fa2024",
    storageBucket: "journal-project-comp585-fa2024.firebasestorage.app",
    messagingSenderId: "715827816927",
    appId: "1:715827816927:web:389737f8722470b2fcbc6a",
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: "AIzaSyD4FNzAV7FackxyoWOvTh9alFYq_FdGN-Q",
    authDomain: "journal-project-comp585-fa2024.firebaseapp.com",
    projectId: "journal-project-comp585-fa2024",
    storageBucket: "journal-project-comp585-fa2024.firebasestorage.app",
    messagingSenderId: "715827816927",
    appId: "1:715827816927:web:389737f8722470b2fcbc6a",
    iosClientId: "YOUR_IOS_CLIENT_ID",
    iosBundleId: "YOUR_IOS_BUNDLE_ID",
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: "AIzaSyD4FNzAV7FackxyoWOvTh9alFYq_FdGN-Q",
    authDomain: "journal-project-comp585-fa2024.firebaseapp.com",
    projectId: "journal-project-comp585-fa2024",
    storageBucket: "journal-project-comp585-fa2024.firebasestorage.app",
    messagingSenderId: "715827816927",
    appId: "1:715827816927:web:389737f8722470b2fcbc6a",
    iosClientId: "YOUR_IOS_CLIENT_ID",
    iosBundleId: "YOUR_IOS_BUNDLE_ID",
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: "AIzaSyD4FNzAV7FackxyoWOvTh9alFYq_FdGN-Q",
    authDomain: "journal-project-comp585-fa2024.firebaseapp.com",
    projectId: "journal-project-comp585-fa2024",
    storageBucket: "journal-project-comp585-fa2024.firebasestorage.app",
    messagingSenderId: "715827816927",
    appId: "1:715827816927:web:389737f8722470b2fcbc6a",
  );
}
