// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD4FNzAV7FackxyoWOvTh9alFYq_FdGN-Q',
    appId: '1:715827816927:web:389737f8722470b2fcbc6a',
    messagingSenderId: '715827816927',
    projectId: 'journal-project-comp585-fa2024',
    authDomain: 'journal-project-comp585-fa2024.firebaseapp.com',
    storageBucket: 'journal-project-comp585-fa2024.firebasestorage.app',
    measurementId: 'G-HV25LL906W',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCllvjGgZ7jQWf979yQE-9is2OjkFcBfhs',
    appId: '1:715827816927:ios:b3a2d9a4441ba7cefcbc6a',
    messagingSenderId: '715827816927',
    projectId: 'journal-project-comp585-fa2024',
    storageBucket: 'journal-project-comp585-fa2024.firebasestorage.app',
    iosBundleId: 'com.example.journalProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCllvjGgZ7jQWf979yQE-9is2OjkFcBfhs',
    appId: '1:715827816927:ios:b3a2d9a4441ba7cefcbc6a',
    messagingSenderId: '715827816927',
    projectId: 'journal-project-comp585-fa2024',
    storageBucket: 'journal-project-comp585-fa2024.firebasestorage.app',
    iosBundleId: 'com.example.journalProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD4FNzAV7FackxyoWOvTh9alFYq_FdGN-Q',
    appId: '1:715827816927:web:41ac9560638b96ebfcbc6a',
    messagingSenderId: '715827816927',
    projectId: 'journal-project-comp585-fa2024',
    authDomain: 'journal-project-comp585-fa2024.firebaseapp.com',
    storageBucket: 'journal-project-comp585-fa2024.firebasestorage.app',
    measurementId: 'G-GKGE8FB01Q',
  );
}
